"""add consultations + medications

Revision ID: f7c3888240e1
Revises: 380fb8384de4
Create Date: 2025-10-24 19:23:49.336012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7c3888240e1'
down_revision: Union[str, Sequence[str], None] = '380fb8384de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dosage', sa.String(length=120), nullable=False),
    sa.Column('frequency', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'completed', name='medstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_patient_id'), 'medications', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medications_status'), 'medications', ['status'], unique=False)
    op.create_table('consultations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_date'), 'consultations', ['date'], unique=False)
    op.create_index(op.f('ix_consultations_doctor_id'), 'consultations', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_consultations_patient_id'), 'consultations', ['patient_id'], unique=False)
    op.drop_index(op.f('ix_appt_clinic'), table_name='appointments')
    op.drop_index(op.f('ix_appt_doctor_clinic_starts'), table_name='appointments')
    op.drop_index(op.f('ix_appt_patient'), table_name='appointments')
    op.drop_index(op.f('ix_appt_starts'), table_name='appointments')
    op.drop_index(op.f('ix_appt_status'), table_name='appointments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appt_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('ix_appt_starts'), 'appointments', ['starts_at'], unique=False)
    op.create_index(op.f('ix_appt_patient'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appt_doctor_clinic_starts'), 'appointments', ['doctor_id', 'clinic_id', 'starts_at'], unique=False)
    op.create_index(op.f('ix_appt_clinic'), 'appointments', ['clinic_id'], unique=False)
    op.drop_index(op.f('ix_consultations_patient_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_doctor_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_date'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_medications_status'), table_name='medications')
    op.drop_index(op.f('ix_medications_patient_id'), table_name='medications')
    op.drop_table('medications')
    # ### end Alembic commands ###
